version: "3"

services:
  web:
    build: .
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 9000"
    ports:
      - 9000:9000
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - net

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  index_data:
    driver: local
  backups:
    driver: local
